name: Partitioned Worker CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Clone Repository

    - name: Install JDK 12
      uses: actions/setup-java@v1
      with:
        java-version: 12

    - name: Setup Maven
      uses: aahmed-se/setup-maven@v3

    - name: Build
      run: mvn -B -U clean package